# Site settings

title: Rachel Friedman
email: therachelfriedman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
paginate: 5
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

github_username:  rlfriedm

# Build settings
markdown: kramdown
